
[general]
	allowed_servers = "your.server.here"
	announce_new_song = 0
	link_mode = 1
	send_the_essential_packets = false
	first_time = false
	mod_mode = -1
	notification_album_art_location = 1
	send_the_packets = false
	send_songs_to_servers = false
	announcement_message = "&aCraftify > &7Now Playing: &b${song} by ${artists}"
	music_service = "disabled"

[rendering]
	controls = false
	display_mode = 2
	position_x_offset = 0.0
	position_y_offset = 0.0
	anchor_point = 0
	render_type = 2

[login]
	refresh_token = ""
	spotify_login_token = ""
	login_button = "login"
	ytmd_password = ""
	service_port = 8880
	ytmd_token = ""

[servers]
	send_songs_to_servers = false
	allowed_servers = ""

