# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"

# Light sources settings.
[light_sources]
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Enable block entities light source.
	block_entities = true
	# Enable entities light source.
	entities = true
	# Enable first-person player light source.
	self = true
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				axolotl = true
				egg = true
				allay = true
				llama = true
				bat = true
				husk = true
				experience_bottle = true
				rabbit = true
				silverfish = true
				firework_rocket = true
				drowned = true
				item = true
				goat = true
				horse = true
				vindicator = true
				minecart = true
				spectral_arrow = true
				llama_spit = true
				glow_item_frame = false
				parrot = true
				creeper = true
				lightning_bolt = true
				ravager = true
				tropical_fish = true
				slime = true
				pillager = true
				area_effect_cloud = true
				blaze = true
				piglin = true
				endermite = true
				zombie = true
				ender_pearl = true
				guardian = true
				fireball = true
				illusioner = true
				wither_skull = true
				eye_of_ender = true
				wolf = true
				zombie_villager = true
				tnt_minecart = true
				elder_guardian = true
				chest_boat = true
				boat = true
				small_fireball = true
				strider = true
				cave_spider = true
				witch = true
				cod = true
				spider = true
				panda = true
				bee = true
				arrow = true
				cow = true
				magma_cube = true
				pig = true
				skeleton = true
				frog = true
				hoglin = true
				armor_stand = true
				experience_orb = true
				dolphin = true
				stray = true
				turtle = true
				shulker = true
				salmon = true
				wandering_trader = true
				wither_skeleton = true
				vex = true
				piglin_brute = true
				ocelot = true
				furnace_minecart = true
				item_frame = true
				phantom = true
				ender_dragon = true
				leash_knot = true
				evoker = true
				glow_squid = true
				warden = true
				squid = true
				shulker_bullet = true
				enderman = true
				dragon_fireball = true
				chicken = true
				trader_llama = true
				donkey = true
				fox = true
				iron_golem = true
				zombified_piglin = true
				cat = true
				ghast = true
				sheep = true
				player = true
				pufferfish = true
				potion = true
				trident = true
				villager = true
				skeleton_horse = true
				polar_bear = true
				hopper_minecart = true
				painting = true
				wither = true
				zombie_horse = true
				camel = true
				block_display = true
				chest_minecart = true
				command_block_minecart = true
				end_crystal = true
				evoker_fangs = true
				falling_block = true
				giant = true
				interaction = true
				item_display = true
				marker = true
				mooshroom = true
				mule = true
				sniffer = true
				snow_golem = true
				snowball = true
				spawner_minecart = true
				tadpole = true
				text_display = true
				tnt = true
				zoglin = true
				fishing_bobber = true

			[light_sources.settings.entities.farmersdelight]
				rotten_tomato = true

			[light_sources.settings.entities.crittersandcompanions]
				dragonfly = true
				leaf_insect = true
				shima_enaga = true
				koi_fish = true
				dumbo_octopus = true
				otter = true
				red_panda = true
				sea_bunny = true
				ferret = true

			[light_sources.settings.entities.naturalist]
				deer = true
				snail = true
				alligator = true
				canary = true
				firefly = true
				rhino = true
				bluejay = true
				coral_snake = true
				snake = true
				cardinal = true
				vulture = true
				catfish = true
				robin = true
				boar = true
				bass = true
				tortoise = true
				duck = true
				butterfly = true
				giraffe = true
				bear = true
				lizard = true
				zebra = true
				rattlesnake = true
				elephant = true
				lion = true
				hippo = true

			[light_sources.settings.entities.charm]
				moobloom = true
				chair = true
				endermite_powder = true
				coral_squid = true

			[light_sources.settings.entities.supplementaries]
				red_merchant = true

			[light_sources.settings.entities.deeperdarker]
				shattered = true
				stalker = true
				shriek_worm = true
				sculk_centipede = true
				sculk_leech = true
				chest_boat = true
				boat = true
				sculk_snapper = true

			[light_sources.settings.entities.friendsandfoes]
				copper_golem = true
				glare = true
				player_illusion = true
				moobloom = true
				mauler = true
				iceologer = true
				wildfire = true
				ice_chunk = true
				tuff_golem = true
				rascal = true

			[light_sources.settings.entities.lootr]
				lootr_minecart = true

			[light_sources.settings.entities.adorn]
				seat = true

			[light_sources.settings.entities.angling]
				sea_slug = true
				mahi_mahi = true
				anomalocaris = true
				crab = true
				seahorse = true
				bubble_eye = true

			[light_sources.settings.entities.create]
				super_glue = true
				stationary_contraption = true
				contraption = true
				gantry_contraption = true
				carriage_contraption = true
				crafting_blueprint = true
				potato_projectile = true
				seat = true

			[light_sources.settings.entities.immersive_aircraft]
				airship = true
				cargo_airship = true
				biplane = true
				gyrodyne = true
				quadrocopter = true

			[light_sources.settings.entities.creeperoverhaul]
				cave_creeper = true
				snowy_creeper = true
				hills_creeper = true
				dripstone_creeper = true
				desert_creeper = true
				spruce_creeper = true
				badlands_creeper = true
				bamboo_creeper = true
				jungle_creeper = true
				savannah_creeper = true
				mushroom_creeper = true
				swamp_creeper = true
				dark_oak_creeper = true
				beach_creeper = true
				ocean_creeper = true

			[light_sources.settings.entities.wildlife]
				horseshoecrab = true
				sanddollar = true
				starfish = true
				hermitcrab = true
				clam = true
				seaurchin = true
				lark = true
				crab = true
				sparrow = true
				badger = true
				ladybug = true
				meadowlark = true
				dragonfly = true
				flycatcher = true
				bluebird = true
				oriole = true
				sunflowerbeetle = true
				ant = true
				hamster = true
				iguana = true
				june_beetle = true
				armadillo = true
				spider = true
				gecko = true
				milk_snake = true
				anteater = true
				python = true
				king_snake = true
				alligator = true
				glasswing_butterfly = true
				chameleon = true
				bluegill = true
				goldfish = true
				staghorn_beetle = true
				snail = true
				bettafish = true
				koi = true
				rainbow_trout = true
				prawn = true
				phoebe = true
				rhino_beetle = true
				spicebush_butterfly = true
				goldfinch = true
				ferret = true
				hammerhead_shark = true
				mantaray = true
				stingray = true
				jellyfish = true
				glow_jellyfish = true
				seahorse = true
				anglerfish = true
				catfish = true
				shrimp = true
				grass_snake = true
				hedgehog = true
				monkey = true
				boar = true
				deer = true
				capybara = true
				possum = true
				cricket = true
				porcupine = true
				tiger_butterfly = true
				robin = true
				white_eye = true
				monarch_butterfly = true
				wren = true
				stickbug = true
				towhee = true

			[light_sources.settings.entities.fishofthieves]
				plentifin = true
				ancientscale = true
				pondie = true
				splashtail = true
				wildsplash = true
				islehopper = true
				devilfish = true
				battlegill = true
				wrecker = true
				stormfish = true

			[light_sources.settings.entities.wilderwild]
				tumbleweed = true
				firefly = true
				ancient_horn_projectile = true
				jellyfish = true
				coconut = true
				chest_bubbler = true
				sculk_spreader = true

			[light_sources.settings.entities.betternether]
				firefly = true
				hydrogen_jellyfish = true
				naga = true
				flying_pig = true
				jungle_skeleton = true
				skull = true
				naga_projectile = true

			[light_sources.settings.entities.bclib]
				chair = true

			[light_sources.settings.entities.betterarcheology]
				bombentity = true

			[light_sources.settings.entities.betterend]
				dragonfly = true
				end_slime = true
				end_fish = true
				shadow_walker = true
				cubozoa = true
				silk_moth = true

			[light_sources.settings.entities.dawn]
				flying_block = true
				custom_tnt = true

			[light_sources.settings.entities.immersive_paintings]
				painting = true
				glow_painting = true
				graffiti = true
				glow_graffiti = true

			[light_sources.settings.entities.railways]
				benchcart = true
				jukeboxcart = true
				conductor = true

			[light_sources.settings.entities.regions_unexplored]
				boat = true
				chest_boat = true

			[light_sources.settings.entities.terraform]
				boat = true
				chest_boat = true

			[light_sources.settings.entities.universal_graves]
				xp = true

			[light_sources.settings.entities.promenade]
				duck = true
				lush_creeper = true
				capybara = true
				sunken_skeleton = true

			[light_sources.settings.entities.endermanoverhaul]
				cave_enderman = true
				badlands_enderman = true
				desert_enderman = true
				ocean_enderman = true
				mushroom_fields_enderman = true
				dark_oak_enderman = true
				end_enderman = true
				snowy_enderman = true
				flower_fields_enderman = true

			[light_sources.settings.entities.ad_astra]
				tier_1_rocket = true
				lander = true
				corrupted_lunarian = true
				star_crawler = true
				ice_spit = true
				lunarian = true
				tier_4_rocket = true
				glacian_ram = true

