# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"

# Light sources settings.
[light_sources]
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Enable block entities light source.
	block_entities = true
	# Enable entities light source.
	entities = true
	# Enable first-person player light source.
	self = true
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				axolotl = true
				egg = true
				allay = true
				llama = true
				bat = true
				husk = true
				experience_bottle = true
				rabbit = true
				silverfish = true
				firework_rocket = true
				drowned = true
				item = true
				goat = true
				horse = true
				vindicator = true
				minecart = true
				spectral_arrow = true
				llama_spit = true
				glow_item_frame = false
				parrot = true
				creeper = true
				lightning_bolt = true
				ravager = true
				tropical_fish = true
				slime = true
				pillager = true
				area_effect_cloud = true
				blaze = true
				piglin = true
				endermite = true
				zombie = true
				ender_pearl = true
				guardian = true
				fireball = true
				illusioner = true
				wither_skull = true
				eye_of_ender = true
				wolf = true
				zombie_villager = true
				tnt_minecart = true
				elder_guardian = true
				chest_boat = true
				boat = true
				small_fireball = true
				strider = true
				cave_spider = true
				witch = true
				cod = true
				spider = true
				panda = true
				bee = true
				arrow = true
				cow = true
				magma_cube = true
				pig = true
				skeleton = true
				frog = true
				hoglin = true
				armor_stand = true
				experience_orb = true
				dolphin = true
				stray = true
				turtle = true
				shulker = true
				salmon = true
				wandering_trader = true
				wither_skeleton = true
				vex = true
				piglin_brute = true
				ocelot = true
				furnace_minecart = true
				item_frame = true
				phantom = true
				ender_dragon = true
				leash_knot = true
				evoker = true
				glow_squid = true
				warden = true
				squid = true
				shulker_bullet = true
				enderman = true
				dragon_fireball = true
				chicken = true
				trader_llama = true
				donkey = true
				fox = true
				iron_golem = true
				zombified_piglin = true
				cat = true
				ghast = true
				sheep = true
				player = true
				pufferfish = true
				potion = true
				trident = true
				villager = true
				skeleton_horse = true
				polar_bear = true
				hopper_minecart = true
				painting = true
				wither = true
				zombie_horse = true

			[light_sources.settings.entities.farmersdelight]
				rotten_tomato = true

			[light_sources.settings.entities.crittersandcompanions]
				dragonfly = true
				leaf_insect = true
				shima_enaga = true
				koi_fish = true
				dumbo_octopus = true
				otter = true
				red_panda = true
				sea_bunny = true
				ferret = true

			[light_sources.settings.entities.naturalist]
				deer = true
				snail = true
				alligator = true
				canary = true
				firefly = true
				rhino = true
				bluejay = true
				coral_snake = true
				snake = true
				cardinal = true
				vulture = true
				catfish = true
				robin = true
				boar = true
				bass = true
				tortoise = true
				duck = true
				butterfly = true
				giraffe = true
				bear = true
				lizard = true
				zebra = true
				rattlesnake = true
				elephant = true
				lion = true
				hippo = true

			[light_sources.settings.entities.charm]
				moobloom = true
				chair = true
				endermite_powder = true
				coral_squid = true

			[light_sources.settings.entities.supplementaries]
				red_merchant = true

			[light_sources.settings.entities.deeperdarker]
				shattered = true
				stalker = true
				shriek_worm = true
				sculk_centipede = true
				sculk_leech = true
				chest_boat = true
				boat = true
				sculk_snapper = true

			[light_sources.settings.entities.friendsandfoes]
				copper_golem = true
				glare = true
				player_illusion = true
				moobloom = true
				mauler = true
				iceologer = true
				wildfire = true

			[light_sources.settings.entities.lootr]
				lootr_minecart = true

			[light_sources.settings.entities.adorn]
				seat = true

			[light_sources.settings.entities.angling]
				sea_slug = true
				mahi_mahi = true
				anomalocaris = true
				crab = true
				seahorse = true
				bubble_eye = true

			[light_sources.settings.entities.create]
				super_glue = true
				stationary_contraption = true

			[light_sources.settings.entities.immersive_aircraft]
				airship = true
				cargo_airship = true
				biplane = true
				gyrodyne = true
				quadrocopter = true

