disabled = false
paraMax = -1
paraMaxMode = "Standard"
disableWorld = false
disableWorldPostTick = false
disableMultiChunk = false
disableEntity = false
disableTileEntity = false
chunkLockModded = true
teWhiteListString = []
teBlackListString = []
teUnfoundWhiteList = []
teUnfoundBlackList = []
disableEnvironment = false
disableChunkProvider = false
enableChunkTimeout = false
enableTimeoutRegen = false
enableBlankReturn = false
timeoutCount = 5000
opsTracing = false
logCap = 720000
