version = 1
enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 20
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 3.4641016
leavesCullingMode = "DEFAULT"
leavesCullingAmount = 2
includeMangroveRoots = true
powderSnowCulling = true
endGatewayCulling = false
beaconBeamCulling = true
entityModelCulling = false
useOnModdedBlocksByDefault = true

[modCompatibility]
adorn = true
universal_ores = true
farmersdelight = true
seasonsextras = true
bountiful = true
fishofthieves = true
barteringstation = true
betternether = true
reinfshulker = true
betterfurnacesreforged = true
wunderreich = true
betterend = true
friendsandfoes = true
comforts = true
createutilities = true
railways = true
lunade = true
milk = true
archeologyplus = true
wilderwild = true
lolmct = true
lolmcv = true
netherchested = true
customportalapi = true
reinfbarrel = true
supplementaries = true
ubesdelight = true
magnumtorch = true
enchanted-vertical-slabs = true
deeperdarker = true
bedspreads = true
chipped = true
create = true
echochest = true
extended_drawers = true
createoreexcavation = true
minecraft = true
animal_feeding_trough = true
lootr = true
regions_unexplored = true
create_jetpack = true
betterarcheology = true
travelersbackpack = true
createaddition = true
createchunkloading = true
sliceanddice = true
beautify = true
waystones = true
creeperoverhaul = true
tradingpost = true
universal_graves = true
simplevillagers = true
villagersplus = true
toms_storage = true
expandeddelight = true
reinfchest = true
